### ISSUE TITLE
How to parse a bad/different format?

### ISSUE THREAD

**Issue by amine-plutoflume** [GOVCERT-LU/eml_parser#10]
Hello,

This is another question about the parser.  
I am trying to parse the famous Enron dataset EML files:  
`https://archive.org/download/edrm.enron.email.data.set.v2.xml`

(full folder: `https://archive.org/download/edrm.enron.email.data.set.v2.xml/edrm-enron-v2_harris-s_xml.zip` )

Unfortunately, there seems to be messages "not fully/correctly parsed".  
For instance the attached file contains all the needed data (Subject, From address, etc) but these do not appear in the parsing results.  
[3.287079.LTUWB1UEUURY0AMLCGNSEUNK52PXR2CPB.eml.zip](https://github.com/GOVCERT-LU/eml_parser/files/1252149/3.287079.LTUWB1UEUURY0AMLCGNSEUNK52PXR2CPB.eml.zip)

Again, this is just a question to check if this is due to a wrong format of the EML file, or to something I am using incorrectly in the parser.

In advance, thank you for your answer.

Best regards.

**Comment by sim0nx** [comment]
Could you please paste the exact URL for that zip file you were mentioning which does not work as intended?

The link in your message seems to be broken...

**Comment by amine-salem** [comment]
I updated the issue with the raw link, please try to copy/paste it and check if that is ok.  
Best regards

**Comment by sim0nx** [comment]
I found the issue with those eml files. They actually contain an invalid line in the header, which makes the parser ignore anything below.That explains why the result is not as expected.
The wrong line in question is:

`Microsoft Mail Internet Headers Version 2.0`

If you strip that line before handing the input to the parser, everything works fine.

Why that header is present is not clear to me. Searching around brings this up occasionally.
I could work around that but frankly have never seen it before and am not sure the performance impact is worth doing it in the library directly.

Could you please try stripping it before passing the input to the decode function to see if it solves your issue ? (make sure to use http://eml-parser.readthedocs.io/en/latest/api.html#eml_parser.eml_parser.decode_email_b for the parsing)

**Comment by Th4nat0s** [comment]
indeed

Content-Transfer-Encoding: quoted-printable
Microsoft Mail Internet Headers Version 2.0
x-mimeole:  Produced By Microsoft Exchange V6.0.4712.0
content-class:  urn:content-classes:message

Quite complicated to handle since if it's email that break on this line. This line is supposed to be the first one usually. Does it come from an office 365 ?

**Comment by amine-salem** [comment]
Hello, and thanks for explaining the root issue.
I don't know about the compliance of the message, but in the eml files, you can see this

```EDRM Enron Email Data Set has been produced in EML, PST and NSF format by ZL Technologies, Inc. This Data Set is licensed under a Creative Commons Attribution 3.0 United States License <http://creativecommons.org/licenses/by/3.0/us/> . To provide attribution, please cite to "ZL Technologies, Inc. (http://www.zlti.com)."
```

Moreover, many online websites to view EML files are able to parse the message correctly.
Also, there are millions of these messages in the Enron dataset. It would be great to use your library on them.

Best regards
