### ISSUE TITLE
AttributeError: module 'eml_parser' has no attribute 'decode'

### ISSUE THREAD

**Issue by Beelal** [GOVCERT-LU/eml_parser#22]
import datetime
import json
import eml_parser

def json_serial(obj):
    if isinstance(obj, datetime.datetime):
        serial = obj.isoformat()
        return serial

with open('sample.eml', 'rb') as fhdl:
    raw_email = fhdl.read()

parsed_eml = eml_parser.eml_parser.decode_email_b(raw_email)

print(json.dumps(parsed_eml, default=json_serial))

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-04d125c36cc6> in <module>()
     13     raw_email = fhdl.read()
     14 
---> 15 parsed_eml = eml_parser.eml_parser.decode_email_b(raw_email)
     16 
     17 print(json.dumps(parsed_eml, default=json_serial))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/eml_parser/eml_parser.py in decode_email_b(eml_file, include_raw_body, include_attachment_data, pconf, policy)
    320     msg = email.message_from_bytes(eml_file, policy=policy)
    321 
--> 322     return parse_email(msg, include_raw_body, include_attachment_data, pconf)
    323 
    324 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/eml_parser/eml_parser.py in parse_email(msg, include_raw_body, include_attachment_data, pconf)
    426     # parse and decode subject
    427     subject = msg.get('subject', '')
--> 428     headers_struc['subject'] = eml_parser.decode.decode_field(subject)
    429 
    430     # If parsing had problem... report it...

AttributeError: module 'eml_parser' has no attribute 'decode'

**Comment by sim0nx** [comment]
Can you confirm that you are using the latest version i.e. 1.10 ?

**Comment by ashyamzubair** [comment]
I am facing the same issue. I am using the latest version (1.10)

**Comment by daliew** [comment]
I I am using python version 3.6.5,having the same question

**Comment by sim0nx** [comment]
Hmm I am unable to reproduce your erros, also the tests run fine on travis which indicate that there is no general problem.
I suppose you are all using OSX ?

Did you install eml_parser with "pip install" ? System-wide or in a virtual environment ?

**Comment by ashyam95** [comment]
Yes im on OSX. 
Yes i installed eml_parser with pip install. 
System wide.

**Comment by ashyamzubair** [comment]
Yes im on OSX. 
Yes i installed eml_parser with pip install. 
System wide.

**Comment by sim0nx** [comment]
Ok ... not sure what is wrong there. Can you try installing it in a virtualenv to have a clean environment an see if that maybe solves your issues ?

**Comment by mohaissa** [comment]
Hi
I have the same issue.
I hope you find a solution

**Comment by sim0nx** [comment]
Hi @mohaissa 
Are you on OSX as well ?
What python version?
Did you use a virtual environment (without system library support)?
Paste you code snippet here please.

**Comment by mohaissa** [comment]
Hi SimOnx
Thanks for your replay.
I fix it finally, I use Databricks, with Azure ML service.
just restart the cluster.
thanks again

**Comment by sim0nx** [comment]
Hi

Great! Glad it works :-)
