### ISSUE TITLE
attachment's  raw is 'null'

### ISSUE THREAD

**Issue by Yanwenjiepy** [GOVCERT-LU/eml_parser#23]
I use eml_parser parsered an eml file, I set `include_attachment_data=True`, but no attachment data in result.   
The `raw` filed  is `null` in attachment.  
This is result:

`"attachment": [{
		"size": 460916,
		"mime_type_short": "application/x-rar",
		"raw": null,
		"extension": "rar"}]`

So I want to know if there is a problem with my eml file or a problem with this package (if I am offended, I apologize).

Thanks help me !

**Comment by sim0nx** [comment]
No problem :-) glad you found the solution

**Comment by 0x3a** [comment]
Curious, I have the exact same issue...how did you solve it? Every attachment I want to parse has a null value for its raw content.

**Comment by vavanan** [comment]
@sim0nx first for the package, it's awesome. 
I faced with the issue when I have raw:null and include_attachment_data=True. The problem appears when I json.dumps(parsed_eml) - and it's not parsed bytes. To solve this, I just get a dict version, which is returned here: ep.decode_email_bytes(raw_email) and everything works perfectly!

**Comment by sim0nx** [comment]
> @sim0nx thanks for the package, it's awesome.

thnx!

> I faced with the issue when I have raw:null and include_attachment_data=True. The problem appears when I json.dumps(parsed_eml) - and it doesn't parse bytes. To solve this, I just get a dict version, which is returned here: ep.decode_email_bytes(raw_email), and everything works perfectly!

json.dumps cannot handle bytes, but you could add a custom serialisation for that. E.g. something like this:
```python
import eml_parser
import json
import base64

def json_serial(obj):
  if isinstance(obj, bytes):
      return base64.b64encode(obj).decode('ascii')

with open(f, 'rb') as fhdl:
  raw_email = fhdl.read()

o = eml_parser.EmlParser(include_attachment_data=True)
m = o.decode_email_bytes(raw_email)

print(json.dumps(m, default=json_serial))
```
