### ISSUE TITLE
Get empty To, From, Subject and Body of the email through eml_parser

### ISSUE THREAD

**Issue by shaliniidea** [GOVCERT-LU/eml_parser#24]
I get empty To, From, Subject and Body of an email when parsed through eml_parser, but the eml has all these when opened in a mail client.
[8E662D2D05B0.zip](https://github.com/GOVCERT-LU/eml_parser/files/2218365/8E662D2D05B0.zip)

**Comment by sim0nx** [comment]
There are 3 problems with the provided file:
1. The start of the file is invalid as per RFC... you must strip the first lines until "X-Env-Sender:"
2. A to me unknown encoding is used. At lease the headers must be in ASCII format.
3. The file uses the windows newline character

The only blocking part from it being parsed correctly though is point 1. ... if you strip those lines you should be fine.

I might add some magic in the future to ignore invalid start lines, but currently that is not in there.

Hope this helps

**Comment by sim0nx** [comment]
I just released version v1.11 which has a option to skip invalid start of file.
You have to set it manually though as it does have an impact on performance.

Please see the updated documentation:
http://eml-parser.readthedocs.io/en/latest/api.html#module-eml_parser.eml_parser

"ignore_bad_start=True"
