### ISSUE TITLE
Body always empty

### ISSUE THREAD

**Issue by simphide** [GOVCERT-LU/eml_parser#28]
Hi, the parser always shows me, that the body of every mail is emtpy. Everything else, like parsing headers or attachments work.

edit: email body appears to be listed as two attachments (one simple text file and one html text file)

**Comment by sim0nx** [comment]
Hi,
Depends on the structure of the e-mail.
You should possibly include attachment data in that case (https://eml-parser.readthedocs.io/en/latest/api.html#module-eml_parser.eml_parser).

As default there is no attachment or body included in the structure, you have to explicitely ask for that.
