### ISSUE TITLE
Text email not recognized

### ISSUE THREAD

**Issue by rikybordo** [GOVCERT-LU/eml_parser#33]
I've tried to parse an email with the following particular part-message:

```
--_----------=_1235550737204165
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="utf-8"

# HTML CODE HERE
```

This part is recognized as an attachment, but it isn't one, because it's the actual text of the email.

I found a solution by editing the line (116-117) in `eml_parser.py` as follows:

Original

```python
if ('content-disposition' not in msg and msg.get_content_maintype() == 'text') or (
                filename.endswith('.html') or filename.endswith('.htm')):
```

Modified

```python
if (msg.is_attachment() == False and msg.get_content_maintype() == 'text') or (
                filename.endswith('.html') or filename.end
```

Could this solution work for you? Or does this break something I've not thought about?

**Comment by sim0nx** [comment]
Thanks for raising this issue. I have implemented a similar solution to yours in 04aeb2ee104d6c7e808428dccbfcfb07497187e0
