### ISSUE TITLE
include_attachment_data flag not actually implemented

### ISSUE THREAD

**Issue by loochy** [GOVCERT-LU/eml_parser#34]
The `include_attachment_data` flag should be implemented like `include_raw_body`, but the only reference to the flag in `eml_parser.eml_parser.parse_email` is in line 875:

`report_struc['attachment'] = traverse_multipart(msg, 0, include_attachment_data)`

This doesn't stop the processing of the attachment when `include_attachment_data=False`, which affects processing time (when you don't want the attachment) and can throw a lot of binascii errors. 

I suggest an `if include_attachment_data:` around the block from line 874-890 in eml_parser.eml_parser. 

Thanks!

**Comment by sim0nx** [comment]
I see your point though the intention of the current parameter is whether to include the full attachment data or only meta-data. So essentially this is the same as "include_raw_body" which only either includes the body or doesn't. Meta-data is always included.

I am not sure if it makes sense to skip all multi-part parsing regardless of type (i.e. including text/html).

Any chance you could describe your use-case and why this would be useful to you ?

**Comment by gclen** [comment]
We were running into a large number of binascii errors when processing attachments. However, these errors were handled and printed out so we could not handle them properly (though I don't see in the code where it does this now). The use case it to turn of processing of attachments in order to speed up processing as well as get rid of the error messages.

I agree that it doesn't make sense to skip all multi part processing and any changes to the pull request would be greatly appreciated :)

**Comment by sim0nx** [comment]
I see...so for the output part that is easy. eml_parser uses the "logging" framework so you can easily silence it by setting it's logger to not output anything (please see python logging for this).

Regarding the attachment part, I gave it another thought and actually correct my previous reply. Disabling attachment parsing does not disable every multipart parsing. I implemented a your request in: https://github.com/GOVCERT-LU/eml_parser/tree/v1.11.4 with a new flag for "decode_email/decode_email_b".

As noted in the documentation though, HTML files are still parsed as well as "text" marked to be in-lined.

Feedback welcome

**Comment by gclen** [comment]
That looks perfect! Thanks!

**Comment by sim0nx** [comment]
Thanks
