### ISSUE TITLE
should use python-magic instead of file-magic

### ISSUE THREAD

**Issue by godfriedmeesters** [GOVCERT-LU/eml_parser#40]
Problem:

`file-magic` from requirements.txt results in  `AttributeError: module 'magic' has no attribute 'magic_open'.`

Solution:
Use `python-magic `instead of `file-magic` 
`

**Comment by sim0nx** [comment]
That is not really a solution. This library only supports file-magic at the moment.
I suppose it would be doable to support both using an abstraction layer. If you are interested in this please do make a PR.
