### ISSUE TITLE
AttributeError: module 'eml_parser' has no attribute 'EmlParser'

### ISSUE THREAD

**Issue by DannyVim** [GOVCERT-LU/eml_parser#42]
When running the example usage, Python returned such error message:

> AttributeError: module 'eml_parser' has no attribute 'EmlParser'

**Comment by sim0nx** [comment]
Are you sure you are on the latest version 1.12.0 ?
```
pip list
```

**Comment by DannyVim** [comment]
using pip to install, and the version is 1.11.7

**Comment by sim0nx** [comment]
The example is for 1.12.0 onwards. Either update to 1.12.0 or please see the docs for 1.11.7:
https://github.com/GOVCERT-LU/eml_parser/tree/v1.11.7

**Comment by abulka** [comment]
Installing on a Mac 

```
brew install libmagic
pip install eml_parser
```

results in the older version `eml-parser  1.11.7` and not the latest, so have fallen for this documentation confusion too. 

Installing under Ubuntu gives me version `1.14.1` - perhaps the wheels for Mac are not up to date or something? Any chance the situation could be updated for Mac users?

**Comment by sim0nx** [comment]
The wheels are platform independent since this is only pure python code.
My guess would be that you are using python < 3.7 ?
Latest ubuntu gives you python 3.8.

**Comment by abulka** [comment]
Yes, I was using Python 3.6. 

Now that I have upgraded to Python 3.7 the latest version of eml_parser has appeared. Thanks!

**Comment by sim0nx** [comment]
Glad that worked :-)
