### ISSUE TITLE
Text attachments are not retrieved

### ISSUE THREAD

**Issue by serserar** [GOVCERT-LU/eml_parser#43]
Hi,

I'm trying to parse eml files with text attachments, example : 

--===============0219148833355454106==
Content-Type: text/plain; Name="text.txt"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="text.txt"

TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdCwg
c2VkIGRvIGVpdXNtb2QgdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWdu
YSBhbGlxdWEuIFV0IGVuaW0gYWQgbWluaW0gdmVuaWFtLCBxdWlzIG5vc3RydWQgZXhlcmNpdGF0
aW9uIHVsbGFtY28gbGFib3JpcyBuaXNpIHV0IGFsaXF1aXAgZXggZWEgY29tbW9kbyBjb25zZXF1
YXQuIER1aXMgYXV0ZSBpcnVyZSBkb2xvciBpbiByZXByZWhlbmRlcml0IGluIHZvbHVwdGF0ZSB2
ZWxpdCBlc3NlIGNpbGx1bSBkb2xvcmUgZXUgZnVnaWF0IG51bGxhIHBhcmlhdHVyLiBFeGNlcHRl
dXIgc2ludCBvY2NhZWNhdCBjdXBpZGF0YXQgbm9uIHByb2lkZW50LCBzdW50IGluIGN1bHBhIHF1
aSBvZmZpY2lhIGRlc2VydW50IG1vbGxpdCBhbmltIGlkIGVzdCBsYWJvcnVtLg==

the problem seems to occur when parsing the message, at line 850 (eml_parser.py) :

`if ('content-disposition' in lower_keys and msg.get_content_disposition() != 'inline') \
            or msg.get_content_maintype() != 'text':`

always enters in the second condition ( except when the attachment is text )

Thanks.

**Comment by sim0nx** [comment]
Hi,
Could you please state the current outcome and your expected outcome ?
If you don't mind, please put a sample e-mail somewhere (e.g. a gist) so I can have a look from there.

**Comment by serserar** [comment]
Hi, 

I attached a sample eml file to reproduce the issue, the eml_file contains three attachments, but only one is recovered when parsing the file, none of the 'text/plain' attachments are recovered.

thanks.
