### ISSUE TITLE
Memory leak / Infinite loop with eml attachment

### ISSUE THREAD

**Issue by kinoute** [GOVCERT-LU/eml_parser#44]
Hey there,

First, thanks for this great library that helps me for over 6 months now.

I recently encountered a problem when I used eml-parser to extract datas from more than 20k emails. After a while, my python process was starting to eat all my 32Gb of RAM. At first, everything was fine, and suddenly, every second, hundreds of megabytes were added and used by the python process where eml-parser works.

I found out what eml file was responsible of the problem but due to confidential issues, I can't upload it. The most important thing I can tell you and I think it's the main problem is: there is an attachment in the eml file to... another eml file. I think maybe the library gets confused and try recursively and indefinitely to parse the eml.

The problem doesn't appear when eml-parser is initialised like this:

```python
parser = eml_parser.EmlParser(include_raw_body=True, include_attachment_data=False, parse_attachments=False)
```

If I set `parse_attachments` to True, it goes forever and eats all my RAM.

![Capture d’écran 2020-07-03 à 00 22 14](https://user-images.githubusercontent.com/623763/86414129-62c5db80-bcc3-11ea-8ee1-3be8f5238c36.png)

**Comment by sim0nx** [comment]
Hi,
I am glad to hear that!

Regarding your problem; is there any chance you could create a dummy EML file which looks like the one you identified as being a problem ?

That would really help to debug this issue.

**Comment by kinoute** [comment]
I can try to edit the eml file to remove some parts while keeping its weird behaviour. Do you have an email address where I could send it to you though? I'm still not comfortable publishing it here. Warning: the email was categorised as Phishing by our analysts.

**Comment by ninoseki** [comment]
One possible cause is that there is an infinite-loop in `traverse_multipart` function.

**Comment by sim0nx** [comment]
> I can try to edit the eml file to remove some parts while keeping its weird behaviour. Do you have an email address where I could send it to you though? I'm still not comfortable about publishing it here. Warning: the email was categorized as Phishing by our analysts.

I send you an e-mail ... please reply with your sample if possible :-)

**Comment by kinoute** [comment]
Sorry for the very late answer,

I don't have this error anymore with the latest version, thanks! Closing.

**Comment by sim0nx** [comment]
> Sorry for the very late answer,
> 
> I don't have this error anymore with the latest version, thanks! Closing.

Thanks for the feedback, good to hear!
