### ISSUE TITLE
Bug - URL not retrieved

### ISSUE THREAD

**Issue by PakitoSec** [GOVCERT-LU/eml_parser#46]
Hello,

Did you forget to extend this list with the previous iteration result ?

https://github.com/GOVCERT-LU/eml_parser/blob/a72d5c2ad53bf91d5d59e3af993c911124e76305/eml_parser/eml_parser.py#L431

Regards,

**Comment by sim0nx** [comment]
Hi,

No I have not, each iteration is over a different part of the eml file.
Line 529 saves each part separately.
