### ISSUE TITLE
Handle python bug 30681 for invalid date parsing

### ISSUE THREAD

**Issue by nth-attempt** [GOVCERT-LU/eml_parser#47]
Currently the code does not handle the bug mentioned here https://bugs.python.org/issue30681

Following part of the code breaks since we are not catching `TypeError` and `ValueError`.
```
  753:      try:
  754:          raw_body.append((encoding, raw_body_str, msg.items()))
  755:      except AttributeError:
```
https://github.com/GOVCERT-LU/eml_parser/blob/master/eml_parser/eml_parser.py#L753-L755

Sample eml that can raise this bug
```
From: <foobar@example.com>
Orig-Date: Wed Jul 2020 23:11:43 +0100
```

**Comment by sim0nx** [comment]
Thanks for the report and the linked issue.
Since the PR was closed without being merged I submitted a new one to hopefully have this fixed upstream (https://github.com/python/cpython/pull/22090).

Further I will how I can work around that issue. Feel free to submit a PR!

**Comment by sim0nx** [comment]
I have just committed a workaround for your issue.
Could you please test the latest master to see if that fixes it ?

**Comment by nth-attempt** [comment]
It worked :)
