### ISSUE TITLE
Infinite wait when parsing specific eml file

### ISSUE THREAD

**Issue by kevin-dunas** [GOVCERT-LU/eml_parser#48]
Hello.
Thank you for library.

A problem occurred during use.

ep = eml_parser.EmlParser(parse_attachments=False)
parsed_eml = ep.decode_email_bytes(raw_email)

I am trying to parse the eml file like this. but specific eml file is infinite wait.
If it is forcibly stopped, the following error occurs.

  File "/usr/local/lib/python3.7/site-packages/eml_parser/eml_parser.py", line 192, in decode_email_bytes
    return self.parse_email()
  File "/usr/local/lib/python3.7/site-packages/eml_parser/eml_parser.py", line 431, in parse_email
    list_observed_urls = self.get_uri_ondata(body_slice)
  File "/usr/local/lib/python3.7/site-packages/eml_parser/eml_parser.py", line 641, in get_uri_ondata
    for match in eml_parser.regex.url_regex_simple.findall(body):

I'm not sure why this is happening.
What is the workaround?

Attach the sample in txt format.

[sample.txt](https://github.com/GOVCERT-LU/eml_parser/files/5225139/sample.txt)

**Comment by sim0nx** [comment]
Hi,

Thank you for reporting this issue. The problem you are experiencing is due the used regex which apparently got stuck infinitely.
I replaced it by a new one which correctly parses your example and should prevent this in the future.

Could you please re-test using the latest master branch of this module ?
```pip install -U git+https://github.com/GOVCERT-LU/eml_parser```

**Comment by kevin-dunas** [comment]
Wow. Thank you for bug fix!
Now it works perfectly!
