### ISSUE TITLE
module 'eml_parser' has no attribute 'EmlParser'

### ISSUE THREAD

**Issue by bgianardo** [GOVCERT-LU/eml_parser#53]
Hello,
I'm using IDLE with python 3.6.1 on Windows 10

I installed the eml_parser library, then I tried to execute the example code from your page.
I get the following error:

_Traceback (most recent call last):
  File "C:\Users\980\Desktop\temp\Thunderbird export\x-spam data extractor.py", line 17, in <module>
    ep = eml_parser.EmlParser()
AttributeError: module 'eml_parser' has no attribute 'EmlParser'_

Can you please help me?

Thanks
Bruno

**Comment by sim0nx** [comment]
Hi,

Only Python version >=3.7 is supported. Upgrading your version should fix this.
Re-open this issue if it does not.

**Comment by bgianardo** [comment]
Hi,
I upgraded to 3.9 and it works!
Thank you very much.
Bruno
