### ISSUE TITLE
Distinguishing the body of attached emails from the main email body

### ISSUE THREAD

**Issue by PatrickH123** [GOVCERT-LU/eml_parser#56]
Hello,

First of all I would like to say that I have been using eml_parser to extract data from emails for a while now and so far I am very happy with it!

One thing that I am struggling with is to distinguish the body of attached emails from a certain email. I have looked through the json multiple times but cannot figure out a good way.

To parse attachments and the full body I am using:
`ep = eml_parser.EmlParser(include_raw_body=True, include_attachment_data=True, parse_attachments=True)
parsed_eml = ep.decode_email_bytes(raw_email)`

This works great for emails that do not have attachments, or emails that have attachments but no attachments that are eml files themselves. If an email is attached to an email, I can correctly read that it is there as it is listed in
`parsed_eml["attachment"]`

But the body of this attached email is appended to the body of the email. So
`parsed_eml["body"][0]["content"]`
would give me the body of the main email in text format. If the main email also has html, I can retrieve the content using
`parsed_eml["body"][1]["content"]`
And the attached email's body in text format can then be retrieved using
`parsed_eml["body"][2]["content"]`
And if the attached email also has HTML then I can retrieve it with
`parsed_eml["body"][3]["content"]`
...etc

This is fine, but problems arise when the main email is only in text format. Because then the first body (body[0]) is the main email, and body[1] would already give me the attached email's body instead of the html of the main email. I currently do not see how I can distinguish the bodies from each other to determine to which email they belong.

I hope I was able to describe the problem in a clear way.

Thank you for your time
Patrick

**Comment by sim0nx** [comment]
Hi Patrick,
Thank you for your feedback, that's nice to hear!

Would you be able to provide me with a sample file so that I can have a closer look at this ?
You should be able to attach it to this issue or feel free to send me an e-mail (have a look at the commit history to find it).

**Comment by PatrickH123** [comment]
Also, the attached email's body can be read by base64 decoding the raw attachment data of the attached email.

For example:
`raw_email = base64.b64decode(parsed_eml["attachment"][0]["raw"])
ep = eml_parser.EmlParser(include_raw_body=True, include_attachment_data=True, parse_attachments=True)
parsed_eml2 = ep.decode_email_bytes(raw_email)
print(json.dumps(parsed_eml2, default=json_serial))`

This parses the attached email with its own attachments and body etc.

So since all the parts of the attached email can already be read separately in this way, why are they also appended to the main email?

Like this I could compare the contents to distinguish, for example:
`if parsed_eml["body"][1]["content"] == parsed_eml2["body"][0]["content"]
    print("Content belongs to an attached email")`

However that does not seem very elegant to me

@sim0nx I just saw your reply pop up while writing this, I have attached a sample file to this message.

[Main email.eml.zip](https://github.com/GOVCERT-LU/eml_parser/files/6003697/Main.email.eml.zip)

**Comment by PatrickH123** [comment]
Oh I forgot to mention that also the attachments of the attached email are appended to the attachment list when parsing the main eml. So now it is also hard to distinguish whether an attachment is from the main email or from an attached email. In the sample file I have attached a txt file to the attached email so you can see this.

**Comment by sim0nx** [comment]
I have had a closer look at this and must admit that the issues you are seeing stem from the goal of this lib to parse an EML file and extract as much information as possible in one go.
So while it does this, this does not suit your use case from what I understand.

What I could suggest is to include the boundary marker in the body parts, e.g. ```"boundary": "_002_070C1162C9794B95A15F18ECE5D38F5Ahotmailcom_"```, that way you could compare it to the boundary marker found in the header of the main e-mail in order to find out of what you are looking at is part of the main e-mail or not.

Besides that I don't think I can do much about the current situation...anything else IMO would require a refactoring of the lib to allow for what it does today, and what you require.

I am open for suggestions though.

**Comment by PatrickH123** [comment]
Thank you for taking a look at this! I have looked at the raw eml file too by opening it with a text editor and saw that the body of the attached email is just appended to the file, so considering this I also think it is correct what this library is doing. I also noticed that every part starts with the boundary, so I think including that would indeed be a good solution. That would make comparison a lot easier already.

Another possibility could be to filter the parts of the eml file by the boundary to identify which email each part belongs to, and then putting separate emails in a list. But, I can totally understand if that requires a lot of work, and might go beyond what this library is supposed to do. For my particular use case it would neither be a necessity. I am already very happy with your proposed solution! It would solve my problem.

**Comment by sim0nx** [comment]
I added the boundary marker in the latest commit (https://github.com/GOVCERT-LU/eml_parser/commit/2f841c6b24fd42b04c5ffffbfef36cd7658d83ad)

This should solve your reported problem. Any feedback welcome :-)

**Comment by PatrickH123** [comment]
This solves the problem of distinguishing different email bodies, thank you very much!

> 
> 
> Oh I forgot to mention that also the attachments of the attached email are appended to the attachment list when parsing the main eml. So now it is also hard to distinguish whether an attachment is from the main email or from an attached email. In the sample file I have attached a txt file to the attached email so you can see this.

Would it also be possible to include the boundary marker for every attachment? Because attachments are still indistinguishable.
