### ISSUE TITLE
Infinite loop in regex searching for URL ending with unicode characters

### ISSUE THREAD

**Issue by cccs-eric** [GOVCERT-LU/eml_parser#63]
I am hitting what appears to be an infinite loop when trying to parse the following eml file:
[eml_sample.txt](https://github.com/GOVCERT-LU/eml_parser/files/7221517/eml_sample.txt)

```python
import eml_parser

f = open("eml_sample.txt", "rb")
data = f.read()
f.close()        

result = eml_parser.eml_parser.decode_email_b(data, include_raw_body=True)
```
The problem is with the following [line](https://github.com/GOVCERT-LU/eml_parser/blob/2732d7dfeb0971665b77ea9541fab81ea284799b/eml_parser/eml_parser.py#L683).  The email body contains a URL that is immediately followed by multiple occurrences or `\xef\xbf\xbd`.  
```
xcxcxcxcxcxcxcxcxcxc
http://xxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx.com������������������������������������������������
```
If I remove those, the parsing is just fine.  It is also fine if I remove only some of them, but the parsing takes longer.  So I assume that it is not an infinite loop, but it rather throws of the regex and creates some kind of cycle...

Is it a problem with the regex, or the way I am reading that file (not decoding Unicode characters)?

**Comment by sim0nx** [comment]
This seems to be related to the regex unfortunately... related report #62 .
Currently the easiest way to work around this seems to be switching to a different regex engine, where the choices currently are pyre2 or regex.
Before doing that, thorough tests have to be made to make sure this does not break things in unexpected ways.

**Comment by sim0nx** [comment]
As I have mentioned in #62, I have added some extra flags using which you can easily test the alternative regex engines (pyre2, regex). See the changelog for details.

Could you please give this is a try and see how it performs for your use-case ?

Whichever you choose will be used over *re*, but regex will take preference if both are installed.

-> Only the main big regular expressions are affected by this. If this proves to be working well as a definitive replacement, I will switch over the simpler ones as well.

**Comment by cccs-eric** [comment]
@sim0nx Thanks for adding the package selection code.  I tested eml-parser with `regex==2021.4.4` and it worked.  No infinite loop.  I didn't try `re2`.  I will switch to `regex` and see how it goes.  But if you have a large suite of regression tests, it would be better than relying on my feedback :)

**Comment by sim0nx** [comment]
:-) thanks for the feedback
