### ISSUE TITLE
Enhancement: Match HTML Anchor href and Image src

### ISSUE THREAD

**Issue by malvidin** [GOVCERT-LU/eml_parser#64]
In the simple URL regex, many URLs that don't include the scheme in the href or src are skipped.  
```
<a target="_blank" href="www.wikipedia.org">
  Wikipedia (opens in new tab)
</a>
```
Should URLs like this be extracted?

**Comment by sim0nx** [comment]
Strictly speaking those are not URLs, on the other hand doing regex searches with optional scheme leads to matching a lot of garbage and possible infinitely running code (regex problems).

Searching for href tags and extracting the content could be an idea though.
Can you do a PR with a proposal ?

**Comment by sim0nx** [comment]
PR merged
