### ISSUE TITLE
"ImportError: cannot import name 'version'" with eml_parser v1.6

### ISSUE THREAD

**Issue by internaut** [GOVCERT-LU/eml_parser#7]
A simple `import eml_parser` fails with version 1.6:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-dbfbe77cbceb> in <module>()
----> 1 import eml_parser

~/.virtualenvs/XXXXX/lib/python3.5/site-packages/eml_parser/__init__.py in <module>()
      7 
      8 from . import eml_parser
----> 9 from . import version
     10 
     11 __version__ = '1.6'

ImportError: cannot import name 'version'
```
v1.5 works (it does not contain the problematic import statement).

Probably a missing file. Since the code for v1.6 is not on github, I can't provide a fix.

**Comment by sim0nx** [comment]
Thanks a lot for pointing both issues out!
I have fixed that issue and it should work fine now. I have also released new versions on pypi and pushed all changes here.

Could you please give it a try?

**Comment by internaut** [comment]
Works now with v1.7, thanks!

**Comment by sim0nx** [comment]
Appreciate your feedback!
