### ISSUE TITLE
can not install the latest version

### ISSUE THREAD

**Issue by Biaocsu** [GOVCERT-LU/eml_parser#70]
```
pip install eml_parser==1.17.0

ERROR: Could not find a version that satisfies the requirement eml_parser==1.17.0 (from versions: 0.9, 1.0, 1.1, 1.3, 1.4, 1.5,
 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.11.1, 1.11.2, 1.11.4, 1.11.5, 1.11.6, 1.11.7)
ERROR: No matching distribution found for eml_parser==1.17.0
```
if I use `pip install eml_parser` gets the version of `1.11.7` and happends to this error:
`AttributeError: module 'eml_parser' has no attribute 'EmlParser'`

**Comment by Biaocsu** [comment]
it seems like there should be `Python versions >=3.7.11`

**Comment by sim0nx** [comment]
What version of Python do you use?

> python -V

**Comment by Biaocsu** [comment]
thanks for you reply, it is the version problem, I update python and solved
