### ISSUE TITLE
How to solve email with pic

### ISSUE THREAD

**Issue by Biaocsu** [GOVCERT-LU/eml_parser#71]
Hi, there. I have eml data which is actually "email writing by picture", so how can I extract the pic from eml?
I can use OCR method to extract text from a pic, but now do not know how to get the pic, whatever advise will be appreciate

**Comment by sim0nx** [comment]
Hi, have a look at the following snippet

```python
import pathlib

import eml_parser

sample = pathlib.Path('samples/sample_attachments.eml')

with sample.open('rb') as fhdl:
    raw_email = fhdl.read()

ep = eml_parser.EmlParser(include_attachment_data=True)
parsed_eml = ep.decode_email_bytes(raw_email)

for attachment in parsed_eml.get('attachment', []):
    if attachment['mime_type_short'] == 'application/pdf':
        print(attachment['raw'])
```

replace the conditional within the for loop with whatever you want to react on.

**Comment by Biaocsu** [comment]
> 

really thanks!
