### ISSUE TITLE
Domain Parser parsing out incorrect CSS/HTML Values

### ISSUE THREAD

**Issue by EdgeSync** [GOVCERT-LU/eml_parser#72]
OS: Centos7 x64
Python Version: 3.9.10
eml_parser version: 1.17.0

Hey there, 

So while parsing emails, I've noticed that the domains coming out of the parser, often some are just random bits of CSS or HTML, and shouldn't be included. 

Example:

[
        "sharepoint.com",
        **"div.msonormal",**
        **"span.msosmartlink",**
        "www2.deloitte.com",
        "www.deloitte.co.uk",
        **"72.0pt",**
        "span.msohyperlink",
         "deloitte.co.uk",
         **"div.wordsection1",**
         "www.w3.org",
         **"5.4pt",**
         **"span.emailstyle19",**
         "schemas.microsoft.com"
    ]

I haven't had a chance to dig into what is causing this, but I'd imagine it is the regex used to parse out domains. Wanted to open an issue to track.

**Comment by sim0nx** [comment]
Hi @EdgeSync 

Please have a try at the new __init__ flags:
- email_force_tld
- domain_force_tld
- ip_force_routable
- include_www
- include_href

There are quite a number of changes in the latest which should fix that behavior. See also https://eml-parser.readthedocs.io/en/latest/api/#eml_parser.eml_parser.EmlParser.__init__ .

The flags are for now disabled by default in order not to change previous behavior.

Do also try to install eml_parser with the *regex* extras options. That will use a non-builtin regex engine which should also give better results overall. This one will become the default in one of the next releases.

**Comment by EdgeSync** [comment]
Hey @sim0nx,

Yep - I've tested with that, and definitely looks way better in the results. I was using the old way of calling the function

`parsed_eml = eml_parser.eml_parser.decode_email_b(email_bytes, include_raw_body=True)`

and changed it to the newer way of calling the function

`ep = eml_parser.EmlParser(include_raw_body=True, email_force_tld=True, domain_force_tld=True)`
`parsed_eml = ep.decode_email_bytes(email_bytes)`

And the few emails I've tested on have perfect URI and Domain outputs.

Thanks for the input - I'll mark as solved!

**Comment by sim0nx** [comment]
Cool thanks for the feedback!
