### ISSUE TITLE
Parsing Fails on Malformed Address Parts

### ISSUE THREAD

**Issue by malvidin** [GOVCERT-LU/eml_parser#76]
If a CR or LF is found in a malformed email address header fields (From/To/etc.), the ValueError breaks the parsing.

The following are the locations that have returned ValueErrors for including a CR or LF:

https://github.com/GOVCERT-LU/eml_parser/blob/c441705c81923beb7f9dc1e839018157b8f28fd6/eml_parser/eml_parser.py#L256-L259

https://github.com/GOVCERT-LU/eml_parser/blob/c441705c81923beb7f9dc1e839018157b8f28fd6/eml_parser/eml_parser.py#L582-L587

https://github.com/GOVCERT-LU/eml_parser/blob/c441705c81923beb7f9dc1e839018157b8f28fd6/eml_parser/eml_parser.py#L814-L817

Example malformed email that causes the issue:
```
From: =?utf-8?q?=0A?= <badname@example.com>
To: =?utf-8?b?Cg==?= <badname@example.com>

Message Body
```

**Comment by sim0nx** [comment]
FYI pypi is in maintenance mode. Update will be pushed asap
