### ISSUE TITLE
import eml_parser returns error

### ISSUE THREAD

**Issue by mohi048** [GOVCERT-LU/eml_parser#8]
1. Environment -:
Python 2.7.10
Virtualenviroment
Installing eml-parser via pip

2. Steps to reproduce:

$ pip install eml-parser
Collecting eml-parser
  Using cached eml_parser-1.7-py2.py3-none-any.whl
Requirement already satisfied: cchardet in /x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages (from eml-parser)
Requirement already satisfied: python-dateutil in /x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages (from eml-parser)
Requirement already satisfied: file-magic in /x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages (from eml-parser)
Requirement already satisfied: typing in /x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages (from eml-parser)
Requirement already satisfied: six>=1.5 in /x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages (from python-dateutil->eml-parser)
Installing collected packages: eml-parser
Successfully installed eml-parser-1.7

(connect_to_cloud) my_pc:ccccc xxxxx$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import eml_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages/eml_parser/__init__.py", line 8, in <module>
    from . import eml_parser
  File "/x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages/eml_parser/eml_parser.py", line 82
    def get_raw_body_text(msg: email.message.Message) -> typing.List[typing.Tuple[typing.Any, typing.Any, typing.Any]]:
                             ^
SyntaxError: invalid syntax

3. Result:-

>>> import eml_parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages/eml_parser/__init__.py", line 8, in <module>
    from . import eml_parser
  File "/x/y/virtuals/connect_to_cloud/lib/python2.7/site-packages/eml_parser/eml_parser.py", line 82
    def get_raw_body_text(msg: email.message.Message) -> typing.List[typing.Tuple[typing.Any, typing.Any, typing.Any]]:
                             ^
SyntaxError: invalid syntax

**Comment by mohi048** [comment]
pulled the latest code from github is having the same behaviour on import.

**Comment by sim0nx** [comment]
Hi,
Thanks for your report!
As noted in the project's readme, version 1.2 was the last one to support Python2.
You do require >=Python3.4, though 3.5 is absolutely recommended.
