### ISSUE TITLE
Error when importing lib: symbol not found 

### ISSUE THREAD

**Issue by amine-salem** [GOVCERT-LU/eml_parser#9]
Hello,

I don't think this is an issue on your side, but you might be able to advise/make the code more generic on different platforms. 
When trying to execute one simple example:

```
import eml_parser
def json_serial(obj):
    if isinstance(obj, datetime.datetime):
        serial = obj.isoformat()
        return serial


with open('sample-message.eml', 'rb') as fhdl:
    raw_email = fhdl.read()

parsed_eml = eml_parser.eml_parser.decode_email_b(raw_email)

print(json.dumps(parsed_eml, default=json_serial))
```

it fails saying 
`AttributeError: dlsym(RTLD_DEFAULT, magic_open): symbol not found`

I am using OSX, python3.6

Could you please help on this?

Thanks in advance.

**Comment by sim0nx** [comment]
Hi,
Thanks for the report.
The code is generic, the problem in my opinion lies in a third-party dependency which is not installed.
I don't have an OSX for testing this myself unfortunately.

You do have the python module file-magic installed, which eml_parser uses if it is available.
According to the error you get I assume that it is unable to load the libmagic library.

Could you please make sure the libmagic library is correctly installed?
I am not really familiar with OSX thus I can't advise you how to install it, according to some snippet this should be doable via brew:
https://gist.github.com/eparreno/1845561


Please let me know if this was of any help and if you got it to work :-)

**Comment by amine-salem** [comment]
indeed, installing libmagic fixed the issue,  
thanks !

**Comment by sim0nx** [comment]
Glad that did the trick :-)

**Comment by ndebard** [comment]
Doesn't work for me:

pn1715628:src nathan$ python3.6
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/magic.py", line 61, in <module>
    _open = _libraries['magic'].magic_open
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
**AttributeError: dlsym(RTLD_DEFAULT, magic_open): symbol not found**
>>> ^D
pn1715628:src nathan$ sudo -H python3.6 -m pip install libmagic
Password:
Requirement already satisfied: libmagic in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
pn1715628:src nathan$

**Comment by sim0nx** [comment]
@ndebard the python module you installed is not the correct one.
eml_parser needs file-magic
If you installed eml_parser using pip, the correct library is already installed.

What you are missing is the libmagic system library (this is not a python library!) as noted in the OSX link I posted earlier:
https://gist.github.com/eparreno/1845561
